sudo: required
language: java
jdk:
  - oraclejdk8
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "TF3eRMjEWX9ByIC2/ECiar4o9dgJYW6a0+DwQ0v0IANAFBvDugpMj9zwhcInzFpvEn1V7nft5T+2CBNcyVppBEdgkTEXO2SQaBZl+DDsO8Svwl3qevK9kDXKKNHb5ojdXk59+oMauNKbBfEV3/8/acVCOOcZTu6DRsq+oxALRv0="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "teverett/paradoxReader"
      description: "Build submitted via Travis CI"
    notification_email: tom@khubla.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan
